### ISSUE TITLE
HW01

### ISSUE THREAD

**Issue by Eugene1992** [Dergachov/JavaStudyPro#1]
Create a Stack data structure which:
- should be generic
- contain `push()` and `pop()` methods for adding and get elements according to the LIFO principle
- implements `Iterable<T>` interface
- contain an inner class as implementation of `Iterator<T>` interface
- covered with documentation

**Comment by Dergachov** [comment]
- Implements  `push()` and `pop()` methods at LIFO principle
  - Add private method with autoresize array stack
  - implements Iterable<T> interface
  - implements an inner class as implementation of Iterator<T> interface
  - Some comments & docs
