### ISSUE TITLE
HW03

### ISSUE THREAD

**Issue by Eugene1992** [Dergachov/JavaStudyPro#2]
1. Write ArayList implementation, should be realized next methods:
- add(T value)
- add(int index, T value)
- get(int index)
- set(int index, T value)
- contains(T value)
- remove(int index)
- iterator()
- size()
2. Write ListTester implementation, which measures the execution time of basic data operations(add, set, get, remove) for `List` interface data structures.

**Comment by Dergachov** [comment]
ArayList realized with next methods:
add(T value)
add(int index, T value)
get(int index)
set(int index, T value)
contains(T value)
remove(int index)
iterator()
size()
