### ISSUE TITLE
LinkedList implementation

### ISSUE THREAD

**Issue by Eugene1992** [Dergachov/JavaStudyPro#3]
Write LinkedList implementation, should be realized next methods:

- add(T value)
- add(int index, T value)
- get(int index)
- set(int index, T value)
- contains(T value)
- remove(int index)
- iterator()
- size()

**Comment by Dergachov** [comment]
Wrote implementation of class MyLinkedList like by class LinkedList with some main methods.

Implementation methods:
- add(T value)
- add(int index, T value)
- get(int index)
- set(int index, T value)
- contains(T value)
- remove(int index)
- iterator()
- size()
